name: delivery_app
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  get_storage: ^2.1.1
  logger: ^2.4.0
  fluttertoast: ^8.2.5
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  geolocator: ^12.0.0
  connectivity_plus: ^6.0.3
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  google_fonts: ^6.2.1

flutter:
  uses-material-design: true
